spring:
  application:
    name: crud
  datasource:
    url: jdbc:mariadb://localhost:3306/employee_manager
    username: employee_manager
    password: nothing
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8082

logging:
  level:
    org:
      hibernate:
        SQL: warn
      springframework:
        security: warn
    root: WARN
